//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.SupplierServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupplierServiceReference.SupplierWebServiceSoap")]
    public interface SupplierWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name AutoSupplierIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoSupplierId", ReplyAction="*")]
        Client.SupplierServiceReference.AutoSupplierIdResponse AutoSupplierId(Client.SupplierServiceReference.AutoSupplierIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoSupplierId", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.SupplierServiceReference.AutoSupplierIdResponse> AutoSupplierIdAsync(Client.SupplierServiceReference.AutoSupplierIdRequest request);
        
        // CODEGEN: Generating message contract since element name SupplierID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertSupplier", ReplyAction="*")]
        Client.SupplierServiceReference.insertSupplierResponse insertSupplier(Client.SupplierServiceReference.insertSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.SupplierServiceReference.insertSupplierResponse> insertSupplierAsync(Client.SupplierServiceReference.insertSupplierRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoSupplierIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoSupplierId", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierServiceReference.AutoSupplierIdRequestBody Body;
        
        public AutoSupplierIdRequest() {
        }
        
        public AutoSupplierIdRequest(Client.SupplierServiceReference.AutoSupplierIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoSupplierIdRequestBody {
        
        public AutoSupplierIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoSupplierIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoSupplierIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierServiceReference.AutoSupplierIdResponseBody Body;
        
        public AutoSupplierIdResponse() {
        }
        
        public AutoSupplierIdResponse(Client.SupplierServiceReference.AutoSupplierIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoSupplierIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoSupplierIdResult;
        
        public AutoSupplierIdResponseBody() {
        }
        
        public AutoSupplierIdResponseBody(string AutoSupplierIdResult) {
            this.AutoSupplierIdResult = AutoSupplierIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertSupplier", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierServiceReference.insertSupplierRequestBody Body;
        
        public insertSupplierRequest() {
        }
        
        public insertSupplierRequest(Client.SupplierServiceReference.insertSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SupplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneNumber;
        
        public insertSupplierRequestBody() {
        }
        
        public insertSupplierRequestBody(string SupplierID, string Name, string Email, string PhoneNumber) {
            this.SupplierID = SupplierID;
            this.Name = Name;
            this.Email = Email;
            this.PhoneNumber = PhoneNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierServiceReference.insertSupplierResponseBody Body;
        
        public insertSupplierResponse() {
        }
        
        public insertSupplierResponse(Client.SupplierServiceReference.insertSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertSupplierResult;
        
        public insertSupplierResponseBody() {
        }
        
        public insertSupplierResponseBody(string insertSupplierResult) {
            this.insertSupplierResult = insertSupplierResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SupplierWebServiceSoapChannel : Client.SupplierServiceReference.SupplierWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplierWebServiceSoapClient : System.ServiceModel.ClientBase<Client.SupplierServiceReference.SupplierWebServiceSoap>, Client.SupplierServiceReference.SupplierWebServiceSoap {
        
        public SupplierWebServiceSoapClient() {
        }
        
        public SupplierWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplierWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.SupplierServiceReference.AutoSupplierIdResponse Client.SupplierServiceReference.SupplierWebServiceSoap.AutoSupplierId(Client.SupplierServiceReference.AutoSupplierIdRequest request) {
            return base.Channel.AutoSupplierId(request);
        }
        
        public string AutoSupplierId() {
            Client.SupplierServiceReference.AutoSupplierIdRequest inValue = new Client.SupplierServiceReference.AutoSupplierIdRequest();
            inValue.Body = new Client.SupplierServiceReference.AutoSupplierIdRequestBody();
            Client.SupplierServiceReference.AutoSupplierIdResponse retVal = ((Client.SupplierServiceReference.SupplierWebServiceSoap)(this)).AutoSupplierId(inValue);
            return retVal.Body.AutoSupplierIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.SupplierServiceReference.AutoSupplierIdResponse> Client.SupplierServiceReference.SupplierWebServiceSoap.AutoSupplierIdAsync(Client.SupplierServiceReference.AutoSupplierIdRequest request) {
            return base.Channel.AutoSupplierIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.SupplierServiceReference.AutoSupplierIdResponse> AutoSupplierIdAsync() {
            Client.SupplierServiceReference.AutoSupplierIdRequest inValue = new Client.SupplierServiceReference.AutoSupplierIdRequest();
            inValue.Body = new Client.SupplierServiceReference.AutoSupplierIdRequestBody();
            return ((Client.SupplierServiceReference.SupplierWebServiceSoap)(this)).AutoSupplierIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.SupplierServiceReference.insertSupplierResponse Client.SupplierServiceReference.SupplierWebServiceSoap.insertSupplier(Client.SupplierServiceReference.insertSupplierRequest request) {
            return base.Channel.insertSupplier(request);
        }
        
        public string insertSupplier(string SupplierID, string Name, string Email, string PhoneNumber) {
            Client.SupplierServiceReference.insertSupplierRequest inValue = new Client.SupplierServiceReference.insertSupplierRequest();
            inValue.Body = new Client.SupplierServiceReference.insertSupplierRequestBody();
            inValue.Body.SupplierID = SupplierID;
            inValue.Body.Name = Name;
            inValue.Body.Email = Email;
            inValue.Body.PhoneNumber = PhoneNumber;
            Client.SupplierServiceReference.insertSupplierResponse retVal = ((Client.SupplierServiceReference.SupplierWebServiceSoap)(this)).insertSupplier(inValue);
            return retVal.Body.insertSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.SupplierServiceReference.insertSupplierResponse> Client.SupplierServiceReference.SupplierWebServiceSoap.insertSupplierAsync(Client.SupplierServiceReference.insertSupplierRequest request) {
            return base.Channel.insertSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.SupplierServiceReference.insertSupplierResponse> insertSupplierAsync(string SupplierID, string Name, string Email, string PhoneNumber) {
            Client.SupplierServiceReference.insertSupplierRequest inValue = new Client.SupplierServiceReference.insertSupplierRequest();
            inValue.Body = new Client.SupplierServiceReference.insertSupplierRequestBody();
            inValue.Body.SupplierID = SupplierID;
            inValue.Body.Name = Name;
            inValue.Body.Email = Email;
            inValue.Body.PhoneNumber = PhoneNumber;
            return ((Client.SupplierServiceReference.SupplierWebServiceSoap)(this)).insertSupplierAsync(inValue);
        }
    }
}
