//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.UserWebServiceSoap")]
    public interface UserWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name AutoPharmacyIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoPharmacyId", ReplyAction="*")]
        Client.UserServiceReference.AutoPharmacyIdResponse AutoPharmacyId(Client.UserServiceReference.AutoPharmacyIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoPharmacyId", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.UserServiceReference.AutoPharmacyIdResponse> AutoPharmacyIdAsync(Client.UserServiceReference.AutoPharmacyIdRequest request);
        
        // CODEGEN: Generating message contract since element name AutoUserIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoUserId", ReplyAction="*")]
        Client.UserServiceReference.AutoUserIdResponse AutoUserId(Client.UserServiceReference.AutoUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.UserServiceReference.AutoUserIdResponse> AutoUserIdAsync(Client.UserServiceReference.AutoUserIdRequest request);
        
        // CODEGEN: Generating message contract since element name PharmacyID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertPharmacy", ReplyAction="*")]
        Client.UserServiceReference.insertPharmacyResponse insertPharmacy(Client.UserServiceReference.insertPharmacyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertPharmacy", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.UserServiceReference.insertPharmacyResponse> insertPharmacyAsync(Client.UserServiceReference.insertPharmacyRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        Client.UserServiceReference.loginResponse login(Client.UserServiceReference.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.UserServiceReference.loginResponse> loginAsync(Client.UserServiceReference.loginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoPharmacyIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoPharmacyId", Namespace="http://tempuri.org/", Order=0)]
        public Client.UserServiceReference.AutoPharmacyIdRequestBody Body;
        
        public AutoPharmacyIdRequest() {
        }
        
        public AutoPharmacyIdRequest(Client.UserServiceReference.AutoPharmacyIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoPharmacyIdRequestBody {
        
        public AutoPharmacyIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoPharmacyIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoPharmacyIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.UserServiceReference.AutoPharmacyIdResponseBody Body;
        
        public AutoPharmacyIdResponse() {
        }
        
        public AutoPharmacyIdResponse(Client.UserServiceReference.AutoPharmacyIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoPharmacyIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoPharmacyIdResult;
        
        public AutoPharmacyIdResponseBody() {
        }
        
        public AutoPharmacyIdResponseBody(string AutoPharmacyIdResult) {
            this.AutoPharmacyIdResult = AutoPharmacyIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoUserId", Namespace="http://tempuri.org/", Order=0)]
        public Client.UserServiceReference.AutoUserIdRequestBody Body;
        
        public AutoUserIdRequest() {
        }
        
        public AutoUserIdRequest(Client.UserServiceReference.AutoUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoUserIdRequestBody {
        
        public AutoUserIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoUserIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.UserServiceReference.AutoUserIdResponseBody Body;
        
        public AutoUserIdResponse() {
        }
        
        public AutoUserIdResponse(Client.UserServiceReference.AutoUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoUserIdResult;
        
        public AutoUserIdResponseBody() {
        }
        
        public AutoUserIdResponseBody(string AutoUserIdResult) {
            this.AutoUserIdResult = AutoUserIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertPharmacyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertPharmacy", Namespace="http://tempuri.org/", Order=0)]
        public Client.UserServiceReference.insertPharmacyRequestBody Body;
        
        public insertPharmacyRequest() {
        }
        
        public insertPharmacyRequest(Client.UserServiceReference.insertPharmacyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertPharmacyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PharmacyID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PharmacyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ContactNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password;
        
        public insertPharmacyRequestBody() {
        }
        
        public insertPharmacyRequestBody(string PharmacyID, string PharmacyName, string Location, string ContactNo, string UserName, string Password) {
            this.PharmacyID = PharmacyID;
            this.PharmacyName = PharmacyName;
            this.Location = Location;
            this.ContactNo = ContactNo;
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertPharmacyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertPharmacyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.UserServiceReference.insertPharmacyResponseBody Body;
        
        public insertPharmacyResponse() {
        }
        
        public insertPharmacyResponse(Client.UserServiceReference.insertPharmacyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertPharmacyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertPharmacyResult;
        
        public insertPharmacyResponseBody() {
        }
        
        public insertPharmacyResponseBody(string insertPharmacyResult) {
            this.insertPharmacyResult = insertPharmacyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public Client.UserServiceReference.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(Client.UserServiceReference.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string UserName, string Password) {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.UserServiceReference.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(Client.UserServiceReference.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserWebServiceSoapChannel : Client.UserServiceReference.UserWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserWebServiceSoapClient : System.ServiceModel.ClientBase<Client.UserServiceReference.UserWebServiceSoap>, Client.UserServiceReference.UserWebServiceSoap {
        
        public UserWebServiceSoapClient() {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.UserServiceReference.AutoPharmacyIdResponse Client.UserServiceReference.UserWebServiceSoap.AutoPharmacyId(Client.UserServiceReference.AutoPharmacyIdRequest request) {
            return base.Channel.AutoPharmacyId(request);
        }
        
        public string AutoPharmacyId() {
            Client.UserServiceReference.AutoPharmacyIdRequest inValue = new Client.UserServiceReference.AutoPharmacyIdRequest();
            inValue.Body = new Client.UserServiceReference.AutoPharmacyIdRequestBody();
            Client.UserServiceReference.AutoPharmacyIdResponse retVal = ((Client.UserServiceReference.UserWebServiceSoap)(this)).AutoPharmacyId(inValue);
            return retVal.Body.AutoPharmacyIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.UserServiceReference.AutoPharmacyIdResponse> Client.UserServiceReference.UserWebServiceSoap.AutoPharmacyIdAsync(Client.UserServiceReference.AutoPharmacyIdRequest request) {
            return base.Channel.AutoPharmacyIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.AutoPharmacyIdResponse> AutoPharmacyIdAsync() {
            Client.UserServiceReference.AutoPharmacyIdRequest inValue = new Client.UserServiceReference.AutoPharmacyIdRequest();
            inValue.Body = new Client.UserServiceReference.AutoPharmacyIdRequestBody();
            return ((Client.UserServiceReference.UserWebServiceSoap)(this)).AutoPharmacyIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.UserServiceReference.AutoUserIdResponse Client.UserServiceReference.UserWebServiceSoap.AutoUserId(Client.UserServiceReference.AutoUserIdRequest request) {
            return base.Channel.AutoUserId(request);
        }
        
        public string AutoUserId() {
            Client.UserServiceReference.AutoUserIdRequest inValue = new Client.UserServiceReference.AutoUserIdRequest();
            inValue.Body = new Client.UserServiceReference.AutoUserIdRequestBody();
            Client.UserServiceReference.AutoUserIdResponse retVal = ((Client.UserServiceReference.UserWebServiceSoap)(this)).AutoUserId(inValue);
            return retVal.Body.AutoUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.UserServiceReference.AutoUserIdResponse> Client.UserServiceReference.UserWebServiceSoap.AutoUserIdAsync(Client.UserServiceReference.AutoUserIdRequest request) {
            return base.Channel.AutoUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.AutoUserIdResponse> AutoUserIdAsync() {
            Client.UserServiceReference.AutoUserIdRequest inValue = new Client.UserServiceReference.AutoUserIdRequest();
            inValue.Body = new Client.UserServiceReference.AutoUserIdRequestBody();
            return ((Client.UserServiceReference.UserWebServiceSoap)(this)).AutoUserIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.UserServiceReference.insertPharmacyResponse Client.UserServiceReference.UserWebServiceSoap.insertPharmacy(Client.UserServiceReference.insertPharmacyRequest request) {
            return base.Channel.insertPharmacy(request);
        }
        
        public string insertPharmacy(string PharmacyID, string PharmacyName, string Location, string ContactNo, string UserName, string Password) {
            Client.UserServiceReference.insertPharmacyRequest inValue = new Client.UserServiceReference.insertPharmacyRequest();
            inValue.Body = new Client.UserServiceReference.insertPharmacyRequestBody();
            inValue.Body.PharmacyID = PharmacyID;
            inValue.Body.PharmacyName = PharmacyName;
            inValue.Body.Location = Location;
            inValue.Body.ContactNo = ContactNo;
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            Client.UserServiceReference.insertPharmacyResponse retVal = ((Client.UserServiceReference.UserWebServiceSoap)(this)).insertPharmacy(inValue);
            return retVal.Body.insertPharmacyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.UserServiceReference.insertPharmacyResponse> Client.UserServiceReference.UserWebServiceSoap.insertPharmacyAsync(Client.UserServiceReference.insertPharmacyRequest request) {
            return base.Channel.insertPharmacyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.insertPharmacyResponse> insertPharmacyAsync(string PharmacyID, string PharmacyName, string Location, string ContactNo, string UserName, string Password) {
            Client.UserServiceReference.insertPharmacyRequest inValue = new Client.UserServiceReference.insertPharmacyRequest();
            inValue.Body = new Client.UserServiceReference.insertPharmacyRequestBody();
            inValue.Body.PharmacyID = PharmacyID;
            inValue.Body.PharmacyName = PharmacyName;
            inValue.Body.Location = Location;
            inValue.Body.ContactNo = ContactNo;
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((Client.UserServiceReference.UserWebServiceSoap)(this)).insertPharmacyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.UserServiceReference.loginResponse Client.UserServiceReference.UserWebServiceSoap.login(Client.UserServiceReference.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string UserName, string Password) {
            Client.UserServiceReference.loginRequest inValue = new Client.UserServiceReference.loginRequest();
            inValue.Body = new Client.UserServiceReference.loginRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            Client.UserServiceReference.loginResponse retVal = ((Client.UserServiceReference.UserWebServiceSoap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.UserServiceReference.loginResponse> Client.UserServiceReference.UserWebServiceSoap.loginAsync(Client.UserServiceReference.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.loginResponse> loginAsync(string UserName, string Password) {
            Client.UserServiceReference.loginRequest inValue = new Client.UserServiceReference.loginRequest();
            inValue.Body = new Client.UserServiceReference.loginRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((Client.UserServiceReference.UserWebServiceSoap)(this)).loginAsync(inValue);
        }
    }
}
